systemIsReady = "System_is_ready1.wav"
sessionStarted = "Session_started1.wav"
trialPaused = "Trial paused1.wav"
trialRestarted = "Trial restarted1.wav"
sessionTerminated = "End tone_1200_sess_completed.wav"
startTone = "Start tone _600.wav"
correctTone = "Correct tone_1000.wav"
incorrectTone = "IncorrectTone.wav"
endTone = "End tone_1200.wav"
criterionAchieved = "Criterion_reached.wav"
criterionNotReached = "Criterion_ not_reached.wav"
acquisitionSessionStarted = "Acquistion_Session_Started.wav"
habitSessionStarted = "Habit_session_started.wav"
extinctionSessionStarted = "Extinction_session_started.wav"
reinstatementSessionStarted = "Reinstatement_session_started.wav"
